services:
  spring-app:
    image: lexilearn-generate-text-service
    container_name: lexilearn-generateTextService-container

    ports:
      - 5004:5004

    environment:
      ENV: 'prod'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      SUBSCRIPTION_KEY: ${SUBSCRIPTION_KEY}
      SERVICE_API_KEY: ${SERVICE_API_KEY}
      USER_JWT_SERCET: ${USER_JWT_SERCET}
      MONGO_URI: ${MONGO_URI}
